name: C++ tests

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        omp: [OFF, ON]
        lapack: [OFF, ON]
    name: "(OpenMP, Lapack) ="

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: build_${{ matrix.omp }}_${{ matrix.lapack }}
      CC: gcc-9
      CXX: g++-9

    steps:
    - uses: actions/checkout@v2

    - name: Build and run C++ tests
      run: |
        sudo apt install liblapacke liblapacke-dev
        mkdir ${BUILD_DIR}
        cd ${BUILD_DIR}

        if [ "${{ matrix.omp }}" = "ON" ]; then
          unset NO_OMP
        else
          export NO_OMP=1
        fi

        if [ "${{ matrix.lapack }}" = "ON" ]; then
          unset NO_LAPACK
        else
          export NO_LAPACK=1
        fi

        echo "OpenMP ${{ matrix.omp }}"
        echo "Lapack ${{ matrix.lapack }}"

        cmake .. -DNO_PYTHON=ON
        cmake --build . -j4
        cd ctests
        ./tests
